name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Verify repository contents
        run: |
          echo "Repository checked out. No build step necessary because the project does not rely on external dependencies."
